### PR TITLE
Implemented groupadd, fix for passwd compile

### PR DESCRIPTION
**Pull request by MggMuggins**
Depends https://github.com/redox-os/users/pull/5

### CODE REVIEW

**Comment by MggMuggins** [comment]
If I push my error handling changes to the other PR, I'll push useradd and those fixes for groupadd here as well. Let me know what you'd like.

**Comment by jackpot51** [comment]
Sure, that is good

**Comment by jackpot51** [comment]
If you can run cargo update and update the Cargo.lock to the newest users commit, I will merge.

**Comment by MggMuggins** [comment]
I think that should do it.

**Comment by jackpot51** [comment]
Thanks!

**Pull request merged**
