### PR TITLE
Goyox86/better errors

### PR DESCRIPTION
**Pull request by goyox86**
⚠️ DO NOT MERGE ⚠️ 

Just a WIP of the recent work on the new errors on `redox_users`.

//cc @MggMuggins

### CODE REVIEW

**Comment by MggMuggins** [comment]
Please make sure the force option for groupadd still works. I can see that being useful in some scripting and sysadmin situations. Check line 75 in the current version, you removed a match arm that implemented `--force`.

**Comment by goyox86** [comment]
Oh yeah will do @MggMuggins. That removed by accident!

**Comment by MggMuggins** [comment]
Meh, at this point I'd like to commit some other stuff here anyway. @jackpot51 please merge this.

**Comment by jackpot51** [comment]
Ok, will do

**Pull request merged**
